# Generated by Django 5.1.3 on 2024-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Загрузите изображение, которое будет использоваться для блока 'Обо мне'.", upload_to='about', verbose_name='Фото')),
                ('full_name', models.CharField(help_text='Введите ваше полное имя, например: Иван Иванович Иванов', max_length=100, verbose_name='ФИО')),
                ('text_about_me', models.TextField(help_text='Расскажите немного о себе, своих увлечениях и достижениях', verbose_name='Описание')),
                ('experience_year', models.CharField(help_text='Укажите ваш профессиональный опыт в годах, например: 5 лет', max_length=100, verbose_name='Опыт работы')),
                ('students_learning', models.CharField(help_text='Укажите количество студентов, которых вы обучили, например: 200', max_length=100, verbose_name='Обученные студенты')),
                ('achievements', models.CharField(help_text="Опишите свои достижения, например: 'Победитель конкурса преподавателей 2023'", max_length=100, verbose_name='Достижения')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
    ]
