# Generated by Django 5.1.3 on 2024-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Введите номер телефона, например: +996555123456', max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Введите электронную почту, например: example@mail.com', max_length=254, verbose_name='Электронная почта')),
                ('whatsapp_url', models.URLField(help_text='Введите ссылку для связи через WhatsApp', verbose_name='URL WhatsApp')),
                ('telegram_number', models.CharField(help_text='Введите номер телефона, связанный с Telegram, например: +996555123456', max_length=15, verbose_name='Номер Telegram')),
                ('telegram_url', models.URLField(help_text='Введите ссылку на профиль Telegram', verbose_name='URL Telegram')),
                ('instagram_account', models.CharField(help_text='Введите имя пользователя Instagram, например: your_account', max_length=50, verbose_name='Аккаунт Instagram')),
                ('instagram_url', models.URLField(help_text='Введите ссылку на профиль Instagram', verbose_name='URL Instagram')),
                ('telegram_bot_username', models.CharField(help_text='Введите @username вашего Telegram-бота', max_length=50, verbose_name='Имя пользователя бота')),
                ('telegram_bot_url', models.URLField(help_text='Введите ссылку на вашего Telegram-бота', verbose_name='URL Telegram-бота')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
