# Generated by Django 5.1.3 on 2024-11-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название теста, которое будет отображаться в интерфейсе.', max_length=100, verbose_name='Название теста')),
                ('description', models.TextField(help_text='Напишите описание теста, которое будет видно пользователю.', verbose_name='Описание теста')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда тест был создан.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления теста.', verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите текст вопроса.', max_length=150, verbose_name='Вопрос')),
                ('option_a', models.TextField(help_text='Введите текст для варианта A.', verbose_name='Вариант A')),
                ('option_b', models.TextField(help_text='Введите текст для варианта B.', verbose_name='Вариант B')),
                ('option_c', models.TextField(help_text='Введите текст для варианта C.', verbose_name='Вариант C')),
                ('option_d', models.TextField(help_text='Введите текст для варианта D.', verbose_name='Вариант D')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Выберите правильный вариант ответа (A, B, C или D).', max_length=1, verbose_name='Правильный вариант')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда вопрос был создан.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления вопроса.', verbose_name='Дата обновления')),
                ('test', models.ForeignKey(help_text='Выберите тест, к которому относится этот вопрос.', on_delete=django.db.models.deletion.CASCADE, to='english_test.testmodel', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['created_at'],
            },
        ),
    ]
