# Generated by Django 5.1.3 on 2024-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Вариант A'), ('B', 'Вариант B'), ('C', 'Вариант C'), ('D', 'Вариант D')], help_text='Выберите правильный вариант ответа (A, B, C или D).', max_length=1, verbose_name='Правильный вариант'),
        ),
    ]
