# Generated by Django 5.1.3 on 2024-11-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0002_alter_testmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='test',
            field=models.ForeignKey(help_text='Выберите тест, к которому относится этот вопрос.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='english_test.testmodel', verbose_name='Тест'),
        ),
    ]
