# Generated by Django 5.1.3 on 2024-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testresult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(choices=[('A', 'Вариант A'), ('B', 'Вариант B'), ('C', 'Вариант C'), ('D', 'Вариант D')], help_text='Введите выбранный вариант ответа (A, B, C или D).', max_length=1, verbose_name='Ответ пользователя'),
        ),
    ]
